spring:

  datasource:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
     # url: jdbc:mysql://139.159.221.252:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
     # username: root
     # password: '!Xx19711021'
      url: jdbc:p6spy:mysql://localhost:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: '123456'

  redis:
   host: localhost
   port: 6379
   password:
  mybatis-plus:
    mapper-locations: classpath*:/mapper/*.xml

  mvc:
    static-path-pattern: /static/**
  freemarker:
    suffix: .ftl
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
    request-context-attribute: base
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

    file:
      upload:
        dir: ${user.dir}/upload

